name: python-project-1
version: 2.1.0
versioned_at: 2026-10-08 17:57
description: Reusable Python project conventions.
entrypoint: README.md
dependencies:
- name: meta
  version: 2.0.2
  constraint: at_least
- name: process
  version: 3.0.2
  constraint: at_least
- name: python-1
  version: 2.0.2
  constraint: at_least
optional_dependencies:
- name: docker-1
  version: 2.0.2
  constraint: at_least
