name: python-project-1
version: 1.2.1
versioned_at: 2026-09-08 19:23
description: Reusable Python project conventions.
entrypoint: README.md
dependencies:
  - name: meta
    version: 1.0.2
    constraint: compatible
  - name: process
    version: 1.2.0
    constraint: compatible
  - name: python-1
    version: 1.0.2
    constraint: compatible
optional_dependencies:
  - name: docker-1
    version: 1.0.2
    constraint: compatible
